# This is the main playbook, which loads all sub-plays with all the tasks and executes them step by step

- hosts: 10.0.249.155
  gather_facts: false
  become: yes
  vars:
    hostname: patrick02
  tasks:
# Install all the prerequisites on the remote PXE-Server. We need some Services which.

    - name: Prepare CoreOS
      ansible.builtin.import_role:
        name: 09_create_coreos_with_butane

# How to install coreos manually on /dev/sda
# sudo coreos-installer install /dev/sda --ignition-url=http://10.0.249.155/butane.ign --insecure-ignition