---
# tasks file for 04_configure_firewall

- name: Open Firewall-Port 21 (FTP)
  firewalld:
    zone: "{{ zone }}"
    port: "{{ ftp }}"
    permanent: yes
    state: enabled
- name: Open Firewall-Port 53 (DNS)
  firewalld:
    zone: "{{ zone }}"
    port: "{{ dns }}"
    permanent: yes
    state: enabled
- name: Open Firewall-Port 67 (DHCP)
  firewalld:
    zone: "{{ zone }}"
    port: "{{ dhcp }}"
    permanent: yes
    state: enabled
- name: Open Firewall-Port 69 (TFTP)
  firewalld:
    zone: "{{ zone }}"
    port: "{{ tftp }}"
    permanent: yes
    state: enabled
- name: Open Firewall-Port 4011 (ProxyDHCP)
  firewalld:
    zone: "{{ zone }}"
    port: "{{ proxydhcp }}"
    permanent: yes
    state: enabled

- name: Reload firewalld config
  service: name=firewalld state=reloaded
# Excute "firewall-cmd --list-all" on remote host to review firewall-settings