---
# tasks file for 02a_modify_dnsmasq_configfile
# Terraform - Create main.tf from template
  - name: "Template the dnsmasq.conf-file"
    template:
      src: "templates/dnsmasq.conf.j2"
      dest: "/etc/dnsmasq.conf"
      mode: "0644"
      owner: "dnsmasq"
      group: "wheel"
      force: yes

# Configure Network-Interface-Name
# - name: Ersetze NETWORK-INTERFACE-NAME
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'NETWORK-INTERFACE-NAME'
#     replace: '{{ network_interface_name }}'
#     #backup: yes

# Configure Subnet Mask
# - name: Ersetze SUBNET-MASK
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'SUBNET-MASK'
#     replace: '{{ subnet_mask }}'

# Configure DHCP-Range-Begin
# - name: Ersetze DHCP-RANGE-START
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'DHCP-RANGE-START'
#     replace: '{{ dhcp_range_start }}'

# Configure DHCP-Range-End
# - name: Ersetze DHCP-RANGE-END
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'DHCP-RANGE-END'
#     replace: '{{ dhcp_range_end }}'

# Configure PXE-Server-IP
# - name: Ersetze PXE-SERVER-IP-ADDRESS
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'PXE-SERVER-IP-ADDRESS'
#     replace: '{{ pxe_server_ip_address }}'

# Configure DHCP-Boot-File-Name
# - name: Ersetze DHCP-BOOT-FILE-NAME
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'DHCP-BOOT-FILE-NAME'
#     replace: '{{ dhcp_boot_file_name }}'

# Configure Default-Gateway
# - name: Ersetze GATEWAY
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'GATEWAY'
#     replace: '{{ gateway_ip_address }}'

# Configure DNS-Server1
# - name: Ersetze DNS1
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'DNS1'
#     replace: '{{ dhcp_boot_option_6_dns1 }}'

# Configure DNS-Server2
# - name: Ersetze DNS2
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'DNS2'
#     replace: '{{ dhcp_boot_option_6_dns2 }}'

# Configure Broadcast-Address
# - name: Ersetze BROADCAST-ADDRESS
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'BROADCAST-ADDRESS'
#     replace: '{{ dhcp_boot_option_28_broadcast_address }}'

# Configure NTP-Server
# - name: Ersetze NTP-SERVER-IP
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'NTP-SERVER-IP'
#     replace: '{{ ntp_ip_address }}'

# Configure TFTP-Root-Directory
# - name: Ersetze TFTP-ROOT-DIRECTORY
#   replace:
#     path: "{{ dnsmasq_config_file }}"
#     regexp: 'TFTP-ROOT-DIRECTORY'
#     replace: '{{ tftp_root_directory }}'
