---
# tasks file for 01_configure_pxe-server
- name: Configure the PXE-Server
  hosts: spielwiese
  become: yes

  tasks:
  # Create the TFTP-Boot-Directory
   - name: CREATE TFTP-BOOT-DIRECTORY
     file:
       path: /var/lib/tftpboot/pxelinux.cfg
       state: directory
  # Copies the pxelinux.cfg-File, which contains the menu_c32 Menu-File to Default-Folder of the TFTP-Server
   - name: COPY pxelinux.cfg TO tftp-boot-directory
     copy:
       src: ./config_files/menu_c32/default_tftp_menu_c32
       dest: /var/lib/tftpboot/pxelinux.cfg/default
       owner: root
       group: root
       mode: 0644
  # Copies all content of the syslinux-files to the tftpboot-directory
   - name: COPY FILES FROM /usr/share/syslinux TO /var/lib/tftpboot
     shell: cp -R /usr/share/syslinux/ /var/lib/tftpboot/
  # Copies the dnsmasq.conf file from local-server to remote-destination
   - name: COPY dnsmasq.conf TO /etc/dnsmasq.conf
     copy:
       src: ./config_files/dnsmasq-config/dnsmasq.conf
       dest: /etc/dnsmasq.conf
       owner: root
       group: root
       mode: 0644
       force: yes
  # Copies the Anaconda-Kickstart-Files to the Public FTP-Folder
   - name: COPY anaconda-ks.cfg TO /var/ftp/pub/
     copy: src=./config_files/kickstart-files/anaconda-ks.cfg dest=/var/ftp/pub/
   - name: COPY clean_minimal_centos761810.cfg TO /var/ftp/pub/
     copy: src=./config_files/kickstart-files/clean_minimal_centos761810.cfg dest=/var/ftp/pub/
   - name: COPY docker.cfg TO /var/ftp/pub/
     copy: src=./config_files/kickstart-files/docker.cfg dest=/var/ftp/pub/
   - name: COPY ks-centos7.6-unattended.cfg TO /var/ftp/pub/
     copy: src=./config_files/kickstart-files/ks-centos7.6-unattended.cfg dest=/var/ftp/pub/
  # Copies the VMLINUX-Kernel-File to the destination under TFTPBOOT/CENTOS7/
   - name: COPY VMLINUZ-Kernel ./config-files/centos7_initrd_vmlinux TO /var/lib/tftpboot/centos7/
     copy: src=./config_files/centos7_initrd_vmlinux/vmlinuz dest=/var/lib/tftpboot/centos7/
  # Copies the INITRD-File to the destination under TFTPBOOT/CENTOS7/
   - name: COPY INITRD-IMAGE ./config-files/centos7_initrd_vmlinux TO /var/lib/tftpboot/centos7/
     copy: src=./config_files/centos7_initrd_vmlinux/initrd.img dest=/var/lib/tftpboot/centos7/
