---
# tasks file for 01_configure_pxe-server
## This task-book creates the tftproot-folder and adds the necessary content to it


# Create the TFTP-Boot-Directory
- name: "Create TFTP-Working Directories on PXE-Server"
  file:
    path: "{{ item }}"
    #owner: root
    #group: root
    #mode: '0755'
    state: directory
    recurse: true
  loop:
    - "{{ tftproot_path }}"
    - "{{ grub_cfg_path }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}"



- name: Copy some needed files from ISOLinux to tftproot-folder
  copy:
    src: "{{ item }}"
    dest: "{{ tftproot_path }}"
    remote_src: true
  loop:
    - "/usr/share/syslinux/pxelinux.0"
    - "/usr/share/syslinux/ldlinux.c32"
    - "/usr/share/syslinux/menu.c32"
    - "/usr/share/syslinux/libutil.c32"

# Mounte NFS-Server-Verzeichnis zum Kopieren des Grub-Bootloaders
- name: "--- 04 - Mounting NFS-Share"
  mount:
    fstype: nfs
    opts: "nfsvers=3,nolock"
    dump: "0"
    passno: "0"
    state: mounted
    src: "{{ nfs_server_name }}:{{ nfs_path }}"
    path: "{{ mount_path }}"

# Extract grubx64.efi
- name: "{{ os_name_rocky89 }} - Extract grubx64.efi"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_rocky89 }}"
    dest: "{{ tftproot_path }}"
    files:
    - EFI/BOOT/grubx64.efi

# Configure DNSMASQ-SELINUX-Policies
- name: Set SELinux boolean tftp_anon_write to true
  seboolean:
    name: tftp_anon_write
    state: true
    persistent: true

- name: Set SELinux boolean tftp_home_dir to true
  seboolean:
    name: tftp_home_dir
    state: true
    persistent: true

- name: Add custom SELinux fcontext
  sefcontext:
    target: "{{ tftproot_path | regex_replace('/$') }}(/.*)?"
    setype: tftpdir_t
    state: present

- name: Restorecon on tftproot_path
  command: "/usr/sbin/restorecon -Rv {{ tftproot_path }}" 

- name: Start and enable dnsmasq persistent
  systemd:
    name: dnsmasq
    state: started
    enabled: yes

