--- 
# tasks file for 04_install_prerequisites
- name: "Install net-tools, wget, nfs-utils, dnsmasq, tftp, pykickstart, selinux-tools and docs" 
  ansible.builtin.yum:
    name: 
      - net-tools.x86_64
      - wget.x86_64
      - nfs-utils.x86_64
      - dnsmasq.x86_64
      - syslinux.x86_64
      - tftp-server.x86_64
      - pykickstart.noarch
      - python3-libsemanage
      - policycoreutils-devel.x86_64
      - setroubleshoot-server.x86_64
    state: present

    
