---
# tasks file for 08_create_a_vm
# Erstelle Arbeitsverzeichnisse
- name: "--- 01 - Create Working Directories on PXE-Server"
  file:
    path: "{{ item }}"
    #owner: root
    #group: root
    #mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ mount_path }}"
    - "{{ mount_path_cdrom }}"

- name: "--- 02 - Create Working Directories on localhost"
  file:
    path: "{{ item }}"
    #owner: root
    #group: root
    #mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ dir_work }}{{ dir_terraform }}{{ hostname }}"
  delegate_to: "127.0.0.1"


- name: "--- 03 - Create Working Directories for TFTP"
  file:
    path: "{{ item }}"
    owner: "{{ dnsmasq_user }}"
    group: "{{ dnsmasq_group }}"
    mode: '0755'
    state: directory
    recurse: true
  with_items:
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos76 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos77 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos78 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos81 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos83 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_rhel77 }}"
    - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_rocky89 }}"
    - "{{ tftproot_path }}pxelinux.cfg/"


# Mounte NFS-Server-Verzeichnis zum Kopieren der Kickstart-Datei
- name: "--- 04 - Mounting NFS-Share"
  mount:
    fstype: nfs
    opts: "nfsvers=3,nolock"
    dump: "0"
    passno: "0"
    state: mounted
    src: "{{ nfs_server_name }}:{{ nfs_path }}"
    path: "{{ mount_path }}"


# pxelinux.cfg > default jinja-Template erstellen 
- name: "--- 05 - Create /pxelinux.cfg/default-file from jinja-Template"
  template:
    src: "templates/{{ jinja_template_default }}"
    dest: "{{ pxelinux_cfg_path }}default"
    mode: "0755"
    owner: "{{ dnsmasq_user }}"
    group: "{{ dnsmasq_group }}"

# Extract the vmlinuz-kernels and initramdisks
- name: "--- 06 - {{ os_name_centos76 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_centos76 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos76 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 07 - {{ os_name_centos77 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_centos77 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos77 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 08 - {{ os_name_centos78 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_centos78 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos78 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 09 - {{ os_name_rhel77 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_rhel77 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_rhel77 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 10 - {{ os_name_centos81 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_centos81 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos81 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 11a - {{ os_name_centos83 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_centos83 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos83 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

- name: "--- 11b - {{ os_name_rocky89 }} - Extract kernel and ramdisk from a ISO"
  iso_extract:
    image: "{{ mount_path }}{{ nfs_path_os_rocky89 }}"
    dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_rocky89 }}/"
    files:
    - isolinux/vmlinuz
    - isolinux/initrd.img

# Default kickstart jinja-Template erstellen 
- name: "--- 12 - Create Kickstart-File from jinja-Template, Save on mounted filesystem from NFS-Server"
  template:
    src: "templates/default-rhel77.cfg"
    dest: "{{ mount_path }}kickstart-configs/{{ hostname }}.cfg"
    mode: "0744"
    owner: "1027"
    group: "users"
    force: yes

# Terraform - Create main.tf from template
- name: "--- 13 - Terraform - Create main.tf from jinja-template"
  template:
    src: "templates/{{ template_terraform_main_tf2 }}"
    dest: "{{ dir_work }}{{ dir_terraform }}{{ hostname }}/main.tf"
    mode: "0644"
    owner: "root"
    group: "root"
    force: yes
  delegate_to: "127.0.0.1"


# Terraform - Create variables.tf from template
- name: "--- 14 - Terraform - Create variables.tf from jinja-template"
  template:
    src: "templates/{{ template_terraform_variables_tf }}"
    dest: "{{ dir_work }}{{ dir_terraform }}{{ hostname }}/variables.tf"
    mode: "0644"
    owner: "root"
    group: "root"
    force: yes
  delegate_to: "127.0.0.1"

# Erzeuge die virtuelle Maschine
- name: "--- 15 Create virtual machine ({{ hostname }}) with terraform"
  raw: "cd {{ dir_work }}{{ dir_terraform }}{{ hostname }} && /usr/local/bin/terraform init && /usr/local/bin/terraform apply -auto-approve"
  delegate_to: "127.0.0.1"
