# This is the main playbook, which loads all sub-plays with all the tasks and executes them step by step

- hosts: pxe
  #vars:
  #  user: root
  #  pass: Test1234
# Install all the prerequisites on the remote PXE-Server. We need some Services which.
- name: This playbook installs all prerequisites
  import_playbook: 01_install_prerequisites.yaml

# Modify the central dnsmasq.conf-File
#- name: This playbook modifies dnsmasq.conf-file
#  import_playbook: 01a_modify_dnsmasq_conf.yaml

# Configure the PXE-Server
- name: This playbook configures the pxe-server
  import_playbook: 02_configure_pxe-server.yaml

# Start and Enable all Daemons
- name: This playbook enables and starts all daemons
  import_playbook: 03_start_and_enable_daemons.yaml

# Set up firewall-daemon
- name: This playbook configures the firewall-rules
  import_playbook: 04_configure_firewall.yaml
