---
- name: Start and Enable all daemons
  hosts: pxe
  become: yes

  tasks:
  # Start and Enable DNSMASQ
  - name: Make sure DNSMASQ service is running
    service:
      state: started
      enabled: yes
      name: dnsmasq
  # Start and Enable VSFTPD
  - name: Make sure VSFTPD service is running
    service:
      state: started
      enabled: yes
      name: vsftpd
