- name: "### --- 01 - Start Playbook create virtual machine --- ###"
  hosts: pxe
  vars_files: 
    - "central_vars.yaml"
  gather_facts: no
  vars_prompt:
# Frage den Hostnamen ab und speichere ihn in einer Variable (max 14 Zeichen, kein FQDN, nur Hostname)
    - name: hostname
      prompt: "Wie ist der Hostname? (14 Zeichen, kein FQDN, nur Hostname): "
      private: no
# Frage das OS ab (centos76, centos77, centos78, rhel81,...)
    - name: os
      prompt: "Welches Betriebssystem? (centos76, centos77, centos78, rhel81): "
      private: no
      
# Beginn TASKs
  tasks:

# Erstelle Arbeitsverzeichnisse
  - name: "--- 01 - Create Working Directories /MNT/NFS-ISO"
    file:
      path: "{{ item }}"
      #owner: root
      #group: root
      #mode: '0755'
      state: directory
      recurse: true
    with_items:
      - "{{ mount_path }}"
      - "{{ mount_path_cdrom }}"

  - name: "--- 02 - Create Working Directories - TFTPROOT"
    file:
      path: "{{ item }}"
      owner: "{{ dnsmasq_user }}"
      group: "{{ dnsmasq_group }}"
      mode: '0755'
      state: directory
      recurse: true
    with_items:
      - "{{ tftproot_path }}{{ kernel_initrd_path }}"
      - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos76 }}"
      - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos77 }}"
      - "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos78 }}"


# Mounte NFS-Server-Verzeichnis zum Kopieren der Kickstart-Datei
  - name: "--- 03 - Mounting NFS-Share"
    mount:
      fstype: nfs
      opts: "nfsvers=3,nolock"
      dump: "0"
      passno: "0"
      state: mounted
      src: "{{ nfs_server_name }}:{{ nfs_path }}"
      path: "{{ mount_path }}"


# Default kickstart jinja-Template erstellen 
  - name: "--- 04 - Create default.cfg from jinja-Template"
    template:
      src: "{{ jinja_template_folder }}{{ jinja_template_default }}"
      dest: "{{ tftproot_path }}{{ pxelinux_cfg_path }}default_ansible"
      mode: "0755"
      owner: "{{ dnsmasq_user }}"
      group: "{{ dnsmasq_group }}"

#  - name: "--- 
  - name: "--- 05 - Mount ISO-File {{ nfs_path_os_centos76 }}"
    shell: "mount -o loop {{ mount_path }}{{ nfs_path_os_centos76 }} {{ mount_path_cdrom }}"

# Kopiere den VMLINUZ-Kernel von CentOS76 nach kernel_initrd auf PXE-Server
  - name: "--- 06 - Kopiere VMLINUZ-Kernel nach TFTP-ROOT"
    copy:
      src: "{{ mount_path_cdrom }}isolinux/vmlinuz"
      dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos76 }}"
      remote_src: yes

# Kopiere den INITRamDisk von CentOS76 nach kernel_initrd auf PXE-Server
  - name: "--- 07 - Kopiere VMLINUZ-Kernel nach TFTP-ROOT"
    copy:
      src: "{{ mount_path_cdrom }}isolinux/initrd.img"
      dest: "{{ tftproot_path }}{{ kernel_initrd_path }}{{ os_name_centos76 }}"
      remote_src: yes
     