hostname: "default.home.local"
os:
nfs_server_name: "nas.home.local"
nfs_server_ip: "10.0.249.150"
nfs_path: "/volume1/nfs-iso/"
nfs_path_os_centos76: "downloaded-iso/linux/CentOS-7-x86_64-DVD-1810.iso"
nfs_path_os_centos77: "downloaded-iso/linux/CentOS-7-x86_64-DVD-1908.iso"
nfs_path_os_centos78: "downloaded-iso/linux/CentOS-7-x86_64-DVD-2003.iso"

mount_path: "/mnt/nfs-iso/"
